apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.artifacts.secretName }}
  namespace: {{ .Release.Namespace }}
stringData:
  ARTIFACT_STORAGE_BACKEND: "s3"
  ARTIFACT_STORAGE_S3_URL: "https://artifacts.{{.Values.global.domain.name}}"
  AWS_REGION: "local"
  ARTIFACT_STORAGE_S3_BUCKET: "semaphore-artifacts"
  AWS_ACCESS_KEY_ID: {{ .Values.global.artifacts.username }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.global.artifacts.password }}
{{- if .Values.global.artifacts.local.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: minio-artifacts
  namespace: {{ .Release.Namespace }}
  labels:
    app: minio-artifacts
    product: semaphoreci
{{- if eq .Values.ingress.className "gce" }}
  annotations:
    cloud.google.com/backend-config: '{"ports": {"9000":"minio-artifacts-backend-config"}}'
    cloud.google.com/neg: '{"ingress": true}'
{{- end }}
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: minio-artifacts
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio-artifacts
  labels:
    app: minio-artifacts
    product: semaphoreci
spec:
  serviceName: minio-artifacts
  replicas: 1
  selector:
    matchLabels:
      app: minio-artifacts
  template:
    metadata:
      labels:
        app: minio-artifacts
        product: semaphoreci
    spec:
      containers:
      - name: minio-artifacts
        image: minio/minio:{{ .Values.global.artifacts.local.version }}
        env:
          - name: MINIO_ROOT_USER
            value: {{ .Values.global.artifacts.username }}
          - name: MINIO_ROOT_PASSWORD
            value: {{ .Values.global.artifacts.password }}
        ports:
        - containerPort: 9000
        command: ["sh"]
        args: ["-c", "mkdir -p /minio-data/semaphore-artifacts && minio server /minio-data"]
        volumeMounts:
        - name: minio-artifacts-storage
          mountPath: "/minio-data"
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 15
  volumeClaimTemplates:
  - metadata:
      name: minio-artifacts-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.global.artifacts.local.size }}
---
{{- if .Values.ingress.enabled }}
{{- if eq .Values.ingress.className "gce" }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: minio-artifacts-backend-config
  namespace: {{ .Release.Namespace }}
spec:
  timeoutSec: 30
  connectionDraining:
    drainingTimeoutSec: 30
  logging:
    enable: true
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 10
    port: 9000
    type: HTTP
    requestPath: /minio/health/live
{{- end }}
{{- end }}
{{- end }}