apiVersion: v1
kind: Service
metadata:
  name: "notifications-v1alpha-public-grpc-api"
spec:
  type: NodePort
  selector:
    app: "notifications"
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
