image: repohub
imageTag: latest
replicas: 1

repohub:
  resources:
    limits:
      cpu: '0.3'
      memory: 300Mi
    requests:
      cpu: '0.1'
      memory: 100Mi

repohubFetcher:
  resources:
    limits:
      cpu: '0.2'
      memory: 300Mi
    requests:
      cpu: '0.03'
      memory: 100Mi

statsd:
  resources:
    limits:
      cpu: "20m"
      memory: "50Mi"
    requests:
      cpu: "5m"
      memory: "25Mi"
