version: "3.6"

services:
  app:
    image: ${IMAGE:-canvas_front-app}:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        - MIX_ENV=${MIX_ENV:-dev}
      ssh:
        - default
      cache_from:
        - ${MAIN_IMAGE:-canvas_front-app}:${IMAGE_TAG:-latest}
    ports:
      - "4000:4000"
      - "5173:5173"

    environment:
      CACHE_PREFIX: "canvas_front/"
      CACHE_HOST: "redis-cache"
      CACHE_PORT: "6379"
      CACHE_POOL_SIZE: "5"
      AMQP_URL: "amqp://rabbitmq:5672"
      SSH_AUTH_SOCK: /ssh-agent
      MIX_ENV: ${MIX_ENV:-dev}
      SEED_CE_FEATURES: "false"
      SEED_CLOUD_MACHINES: "true"
      SEED_SELF_HOSTED_AGENTS: "true"
      EXCLUDE_STUBS: "InstanceConfigMock"
      WORKFLOW_TEMPLATES_YAMLS_PATH: "/app/workflow_templates/saas"
      SEED_PROJECTS: "initializing_failed,zebra,guard,errored,test_results,test_results_debug,after_pipeline,bitbucket"
      SECRET_KEY_BASE: "keyboard-cat-please-use-this-only-for-dev-and-testing-it-is-insecure"
      SESSION_SIGNING_SALT: "keyboard-cat-please-use-this-only-for-dev-and-testing-it-is-insecure"

    links:
      - redis-cache:redis-cache
      - rabbitmq:rabbitmq

    tty: true
    volumes:
      - .:/app

  redis-cache:
    image: "redis:5-buster"
    entrypoint: "redis-server --appendonly yes"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit log_levels [{connection,error}]"
