apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  type: NodePort
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: grpc
      protocol: TCP
      port: 50053
---
apiVersion: v1
kind: Service
metadata:
  name: pbworkflow
spec:
  type: NodePort
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: grpc
      protocol: TCP
      port: 50053
---
apiVersion: v1
kind: Service
metadata:
  name: ppl
spec:
  type: NodePort
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: grpc
      protocol: TCP
      port: 50053
