apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: semaphore
build:
  local: {}
  artifacts:
    - image: ghcr.io/semaphoreio/github_hooks
      custom:
        buildCommand: "APP_ENV=prod make build.skaffold"
      context: github_hooks
    - image: ghcr.io/semaphoreio/auth
      custom:
        buildCommand: "MIX_ENV=prod make build.skaffold"
      context: auth
    - image: ghcr.io/semaphoreio/guard
      custom:
        buildCommand: "MIX_ENV=prod make build.skaffold"
      context: guard
    - image: ghcr.io/semaphoreio/badges
      custom:
        buildCommand: "MIX_ENV=prod make build.skaffold"
      context: badge
    - image: ghcr.io/semaphoreio/front
      custom:
        buildCommand: "MIX_ENV=prod make build.skaffold"
      context: front
    - image: ghcr.io/semaphoreio/ppl
      custom:
        buildCommand: "MIX_ENV=prod make build.skaffold"
      context: plumber/ppl
    - image: ghcr.io/semaphoreio/projecthub-grpc
      custom:
        buildCommand: "MIX_ENV=prod make build.skaffold"
      context: projecthub
    - image: ghcr.io/semaphoreio/projecthub-rest-api
      custom:
        buildCommand: "MIX_ENV=prod make build.skaffold"
      context: projecthub-rest-api
    - image: ghcr.io/semaphoreio/secrethub
      custom:
        buildCommand: "MIX_ENV=prod make build.skaffold"
      context: secrethub
    - image: ghcr.io/semaphoreio/notifications
      custom:
        buildCommand: "MIX_ENV=prod make build.skaffold"
      context: notifications
    - image: ghcr.io/semaphoreio/zebra
      custom:
        buildCommand: "MIX_ENV=prod make build.skaffold"
      context: zebra
    - image: ghcr.io/semaphoreio/periodic-scheduler
      custom:
        buildCommand: "MIX_ENV=prod make build.skaffold"
      context: periodic_scheduler/scheduler
    - image: ghcr.io/semaphoreio/dashboardhub
      custom:
        buildCommand: "MIX_ENV=prod make build.skaffold"
      context: dashboardhub
    - image: ghcr.io/semaphoreio/github_notifier
      custom:
        buildCommand: "MIX_ENV=prod make build.skaffold"
      context: github_notifier
    - image: ghcr.io/semaphoreio/branch_hub
      custom:
        buildCommand: "MIX_ENV=prod make build.skaffold"
      context: branch_hub
    - image: ghcr.io/semaphoreio/public_api
      custom:
        buildCommand: "MIX_ENV=prod make build.skaffold"
      context: public-api/v2
    - image: ghcr.io/semaphoreio/plumber-public
      custom:
        buildCommand: "MIX_ENV=prod make build.skaffold"
      context: public-api/v1alpha
    - image: ghcr.io/semaphoreio/bootstrapper
      custom:
        buildCommand: "APP_ENV=prod make build.skaffold"
      context: bootstrapper
    - image: ghcr.io/semaphoreio/artifacthub
      custom:
        buildCommand: "APP_ENV=prod make build.skaffold"
      context: artifacthub
    - image: ghcr.io/semaphoreio/repository_hub
      custom:
        buildCommand: "MIX_ENV=prod make build.skaffold"
      context: repository_hub
    - image: ghcr.io/semaphoreio/scouter
      custom:
        buildCommand: "MIX_ENV=prod make build.skaffold"
      context: scouter
    - image: ghcr.io/semaphoreio/keycloak-setup
      custom:
        buildCommand: "APP_ENV=prod make build.skaffold"
      context: keycloak/setup
#manifests:
#  helm:
#    releases:
#      - name: keycloak-setup
#        chartPath: keycloak/setup/helm
#        setValueTemplates:
#          imageTag: "{{.IMAGE_FULLY_QUALIFIED_ghcr_io_semaphoreio_keycloak_setup}}"
deploy:
  helm:
    releases:
      - name: semaphore
        chartPath: helm-chart
        valuesFiles:
          - helm-chart/values.yaml
        setValues:
          #keycloak-setup.imageTag: "{{ .IMAGE_TAG_ghcr_io_semaphoreio_keycloak_setup }}"
          global.domain.name: "localhost"
          ingress.className: "traefik"
          ingress.ssl.type: "custom"
        version: 0.1.0
    flags:
      upgrade: ["--timeout", "120m"]
      install: ["--timeout", "120m"]
