apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}"
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: "{{ .Chart.Name }}"
  ports:
    - name: http
      port: 80
      targetPort: 4000
