---
image: repository_hub
imageTag: latest
imagePullSecrets: []

replicas: 1

db:
  name: front
  poolSize: 10

resources:
  limits:
    cpu: 150m
    memory: 300Mi
  requests:
    cpu: 75m
    memory: 150Mi

sidecarEncryptor:
  resources:
    limits:
      cpu: 50m
      memory: 100Mi
    requests:
      cpu: 10m
      memory: 25Mi

statsd:
  resources:
    limits:
      cpu: "20m"
      memory: "50Mi"
    requests:
      cpu: "5m"
      memory: "25Mi"
