apiVersion: v1
kind: Service
metadata:
  name: "auth"
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: "auth"
  ports:
  - name: http
    port: 4000
    targetPort: 4000
