{{- $chartName := regexReplaceAll "_" .Chart.Name "-" }}

apiVersion: v1
kind: Service
metadata:
  name: "{{ $chartName }}"
spec:
  type: NodePort
  selector:
    app: "{{ $chartName }}"
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
