image: branch_hub
imageTag: latest
imagePullSecrets: []

replicas: 1

db:
  name: front
  poolSize: 2

resources:
  limits:
    cpu: 300m
    memory: 200Mi
  requests:
    cpu: 50m
    memory: 100Mi

statsd:
  resources:
    limits:
      cpu: "20m"
      memory: "50Mi"
    requests:
      cpu: "5m"
      memory: "25Mi"