apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-instance-config"
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: "{{ .Chart.Name }}-instance-config"
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
    - name: http
      port: 80
      targetPort: 4004
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-id-http-api"
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: "{{ .Chart.Name }}-id-http-api"
  ports:
    - name: http
      port: 80
      targetPort: 4003
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}"
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: "{{ .Chart.Name }}-api"
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-authentication-api"
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: "{{ .Chart.Name }}-authentication-api"
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-user-api"
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: "{{ .Chart.Name }}-user-api"
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-organization-api"
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: "{{ .Chart.Name }}-organization-api"
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: "semaphore-user-api"
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: "{{ .Chart.Name }}-user-api"
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
