version: "v1.0"
name: Pipeline
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: Block 1
    run:
      when: "change_in('/run', {pipeline_file: 'ignore'})"
    task:
      jobs:
        - commands:
            - exit 127
