{{- if .Values.global.cache.local.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: job-extra-environment
  namespace: {{ .Release.Namespace }}
data:
  SEMAPHORE_TOOLBOX_VERSION: {{ .Values.toolbox.version | b64enc }}
  SEMAPHORE_CACHE_BACKEND: {{ printf "s3" | b64enc }}
  SEMAPHORE_CACHE_S3_URL: {{ printf "http://minio-cache:9000" | b64enc }}
  SEMAPHORE_CACHE_S3_BUCKET: {{ printf "semaphore-cache" | b64enc }}
  SEMAPHORE_CACHE_S3_KEY: {{ .Values.global.cache.username | b64enc }}
  SEMAPHORE_CACHE_S3_SECRET: {{ .Values.global.cache.password | b64enc }}
{{- end }}
