apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.organization.secretName }}
  namespace: {{ .Release.Namespace }}
data:
  name: {{ .Values.global.organization.name | b64enc }}
  endpoint: {{ printf "%s.%s" .Values.global.organization.name .Values.global.domain.name | b64enc }}
