apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.rootUser.secretName }}
  namespace: {{ .Release.Namespace }}
data:
  ROOT_NAME: {{ .Values.global.rootUser.name | b64enc }}
  ROOT_EMAIL: {{ .Values.global.rootUser.email | b64enc }}
{{- if ne .Values.global.rootUser.githubLogin "" }}
  ROOT_GITHUB_LOGIN: {{ .Values.global.rootUser.githubLogin | b64enc }}
{{- end }}
